# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rseg}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yuanyi Zhang"]
  s.date = %q{2009-12-01}
  s.description = %q{A Chinese Word Segmentation(中文分词) routine in pure Ruby}
  s.email = %q{zhangyuanyi@gmail.com}
  s.executables = ["rseg", "rseg_server"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "bin/rseg",
     "bin/rseg_server",
     "dict/dict.hash",
     "lib/app.rb",
     "lib/builder/dict.rb",
     "lib/engines/dict.rb",
     "lib/engines/engine.rb",
     "lib/engines/english.rb",
     "lib/engines/name.rb",
     "lib/engines/number.rb",
     "lib/filters/conjunction.rb",
     "lib/filters/fullwidth.rb",
     "lib/filters/symbol.rb",
     "lib/rseg.rb",
     "public/screen.css",
     "views/index.haml",
     "views/layout.haml"
  ]
  s.homepage = %q{http://github.com/yzhang/rseg}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Chinese Word Segmentation(中文分词) routine in pure Ruby}
  s.test_files = [
    "test/test_auto.rb",
     "test/test_bench.rb",
     "test/test_ent.rb",
     "test/test_finance.rb",
     "test/test_news.rb",
     "test/test_sport.rb",
     "test/test_tech.rb",
     "test/test_web.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
  end
end

